### ISSUE TITLE
使用webpack构建报错

### ISSUE THREAD

**Issue by fefz** [weeksun23/AvalonBootstrap#1]
ERROR in ./demo/index/index.js
Module parse failed: D:\devlop\code\AvalonBootstrap\demo\index\index.js Unexpected token (94:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (94:2)
    at Parser.pp$4.raise (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseBlock (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:2105:24)
    at Parser.pp$1.parseFunction (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:1065:10)
    at Parser.pp$1.parseFunctionStatement (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:818:17)
    at Parser.pp$1.parseStatement (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:694:19)
    at Parser.pp$1.parseTopLevel (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:638:25)
    at Parser.parse (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:516:17)
    at Object.parse (D:\devlop\code\AvalonBootstrap\node_modules\.3.3.0@acorn\dist\acorn.js:3098:39)
    at Parser.parse (D:\devlop\code\AvalonBootstrap\node_modules\.1.15.0@webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (D:\devlop\code\AvalonBootstrap\node_modules\.1.15.0@webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (D:\devlop\code\AvalonBootstrap\node_modules\.0.6.9@webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (D:\devlop\code\AvalonBootstrap\node_modules\.0.6.9@webpack-core\lib\NormalModuleMixin.js:275:25)
    at D:\devlop\code\AvalonBootstrap\node_modules\.0.6.9@webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (D:\devlop\code\AvalonBootstrap\node_modules\.0.9.1@enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at D:\devlop\code\AvalonBootstrap\node_modules\.4.1.11@graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 @ multi index

**Comment by weeksun23** [comment]
解决了
